### PR TITLE
I added a callback function

### PR DESCRIPTION
**Pull request by pelmered**
I added a callback function and updated the readme file.

### CODE REVIEW

**Comment by eroshenko** [comment]
This is merged? Very userfull =(

**Comment by pelmered** [comment]
No, not yet a least.
Untill it's merged you can download my fork at https://github.com/pelmered/jquery-tweetMachine
Hope you will enjoy it :)

**Comment by eroshenko** [comment]
Thanks.
In your fork need update Changelog ;)

**Comment by ryangiglio** [comment]
Sorry, will merge it today!

**Comment by pelmered** [comment]
Great, thanks!

**Comment by ryangiglio** [comment]
Thanks for your help. I had thrown a callback function in mine while I was working on something else but yours is way better.

**Comment by pelmered** [comment]
No problem at all, your welcome! It's even better with your equivalence fix :) 
I'm just glad to help! This is a great plugin!

**Pull request merged**
