### PR TITLE
My little contribution

### PR DESCRIPTION
**Pull request by jdcauley**
Added simple style and classes, swapped ol and li for divs, moved most everything into assets to keep the root trim.  

You know whatever you want.

### CODE REVIEW

**Comment by jdcauley** [comment]
I have no idea is this is even remotely compatible anymore, or if tweetMachine works as all anymore

**Comment by ryangiglio** [comment]
It does indeed still work...unfortunately I haven't been maintaining it very much lately because I've been working on other projects at work instead of the one Tweet Machine was written for, but I still use it in its current state and it's still working! This should definitely still be compatible since not much has changed...I'll do my best to merge it in soon.

**Comment by vesper8** [comment]
hey there... sorry if this is a noob question but I would really like to get the 7 commits that jdcauley was nice enough to share... short of copy/pasting all the changes one at a time.. isn't there an easy way to get all these files at once without them being merged with the main project?

It would be nice if they were merged.. along with a few other enhancements other users have made since the last release.. but if that's not possible to do soon.. I would really like to know how to get these files.. thanks!

**Comment by vesper8** [comment]
I figured it out... they are available here: https://github.com/jdcauley/jquery-tweetMachine

It's just weird that there is no link to this page from this project's page.. I had to look it up manually.

I'm probably missing something... thanks for the contributions in any case!!

**Pull request closed without merging**
